triggers:
  - type: meya.keyword
    properties:
        keyword: weather
states:
    get_city:
        component: meya.input_string
        properties:
            text: What US city?
            output: city
    get_weather:
        component: weather
